project:
  type: website

website:
  title: "About"
  navbar:
    left:
      - text: Bayesian Statistics
        menu: 
          - href: 1_bayesian_statistics/20250414_coin_flipping.ipynb
            text: Basics
          - href: 1_bayesian_statistics/20250410_multivariate_regression.ipynb
            text: Linear Modelling
      - href: 2_time_series/time_series.qmd
        text: Time Series
      - text: Panel Data
        menu: 
          - href: 3_panel_data/20250417_panel_basics.qmd
            text: Panel Data Basics
          - href: 3_panel_data/20250424_re_vs_fe.qmd
            text: Random Effects vs Fxed Effects
          - href: 3_panel_data/20250425_re_vs_eb.qmd
            text: Random Effects vs Empirical Bayes
      - href: 4_decision_trees/decision_trees.qmd
        text: Decision Trees
      - text: Neural Networks
        menu: 
          - href: 5_neural_networks/20250611_basic_nn.ipynb
            text: Simple FFNN
      - href: 6_energy_demand_forecasting/energy_demand_forecasting.qmd
        text: Energy Demand Forecasting
      - href: 7_monetary_policy/monetary_policy.qmd
        text: Monetary Policy

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true