project:
  type: website

website:
  title: "Roberto Martin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 20250417_panel_basics.html
        text: Panel Data

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true